---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cf-api-token
  namespace: traefik-talos
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgCSYLmKFdpt1aRa0jB/vAfBFmOfu5hWOS1lsl323gWcQ7ynOurfWk9B+YTqkD+Gj+Fq7IdlCSfouZe9SzaOAfUdbbqwoO9GCTa5t2eFeDLNNGKnjKfOK0tMu9YqHAjh4M1FJKnGqWL5Z1/lqUGCoOI1vq9E42+QRVIiwvf9N8aEgJcwp5tSaru9xK5a/lR+nGHCCQefR67SdylvqGL4LOahUrC0w5I5vQb6mX1Elre4/cJP+ng+EOyYoIsNmYpZgpyY/zWYr4V7Lj0nsC5D+bpIrQZHtFXNuhMTSy76ZYpYQwvfSOX6ffPGec3NdEKInu7ZsqTPR40axgj6nhoogQc89t0XBvB/bGkYqVSqTdGU/dyK8V+vJGTo+USKwYeSCXCHymBaUMRYkQQGDUMJMXUt+EnhfvRJndnZ2AHUrtbqJ2v4BeRHjR1tqWHKLB5DLUGjjk3P1E/DzEqb3KzTLXqTFIvmoa+nKBi8iMOwT+yUuNxdNtHjFxjixuTxK4nCegN07FqYmIJwlrhJ8oDCfKw16mJtJriLvmnqVwYpw3WWGcpj3/NdcMjfgx8Cj2U9EMROABsyp2H6jlHZc+9JQTUB6+eMW3XkJptncqyEe0zWLdccFdzhyACuziSJ1E70nGa8eSaCwvdm9lP0DMdohJTUebPcJh7eWkNaUXQe68rnl7zZYTYolBQSFDXXici6L1AUS7TGpuJUul8OhIGIcZT20ntgBD89/NNS29xMBvWZbkYpzkqXgEHy
  template:
    metadata:
      name: cf-api-token
      namespace: traefik-talos
