apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: ">=6.0.0 <7.0.0"
    helm:
      values: |
        deploymentMode: SingleBinary
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          schemaConfig:
            configs:
              - from: "2024-01-01"
                store: tsdb
                object_store: filesystem
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h
          storage:
            type: filesystem
          limits_config:
            retention_period: 168h
        singleBinary:
          replicas: 1
          persistence:
            enabled: true
            storageClass: local-path
            size: 20Gi
        backend:
          replicas: 0
        read:
          replicas: 0
        write:
          replicas: 0
        chunksCache:
          enabled: false
        resultsCache:
          enabled: false
        monitoring:
          selfMonitoring:
            enabled: false
        test:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: observability-talos
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
