apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-promtail
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: promtail
    targetRevision: ">=6.0.0 <7.0.0"
    helm:
      values: |
        config:
          clients:
            - url: http://observability-loki-gateway.observability-talos.svc.cluster.local/loki/api/v1/push
        readinessProbe:
          timeoutSeconds: 5
  destination:
    server: https://kubernetes.default.svc
    namespace: observability-talos
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
