apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forgejo-postgresql
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: ">=18.0.0 <19.0.0"
    helm:
      values: |
        architecture: standalone
        auth:
          enablePostgresUser: false
          username: forgejo
          database: forgejo
          existingSecret: forgejo-postgresql-auth
          secretKeys:
            adminPasswordKey: postgres-password
            userPasswordKey: password
        primary:
          persistence:
            enabled: true
            storageClass: forgejo-nfs
            accessModes:
              - ReadWriteOnce
            size: 20Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: forgejo-talos
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
