{
 "title": "Billy",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "BBMB Messages Added",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(bbmb_messages_added_total{job=\"bbmb\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BBMB Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bbmb_uptime_seconds{job=\"bbmb\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress Queue",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bbmb_queue_messages_total{job=\"bbmb\", queue=\"chatting.tasks.v1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BBMB Mem",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bbmb_memory_alloc_bytes{job=\"bbmb\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Egress Queue",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bbmb_queue_messages_total{job=\"bbmb\", queue=\"chatting.egress.v1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Handler Message Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(chatting_message_handler_ingress_published_total{job=\"billy\"}[$__rate_interval])) * 60",
     "legendFormat": "Ingress"
    },
    {
     "expr": "sum(rate(chatting_message_handler_egress_dispatched_total{job=\"billy\"}[$__rate_interval])) * 60",
     "legendFormat": "Egress"
    }
   ]
  },
  {
   "title": "Handler Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "chatting_message_handler_uptime_seconds{job=\"billy\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chatting_message_handler_egress_dispatch_latency_ms_avg{job=\"billy\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Handler Last Loop",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "chatting_message_handler_last_loop_completed_timestamp_seconds{job=\"billy\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}