{
 "title": "Backup (Kite->Backblaze)",
 "time": { "from": "now-14d", "to": "now" },
 "panels": [
  {
   "title": "Latest successful snapshot",
   "type": "logs",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{host=\"kite\", source=\"journal\", systemd_unit=\"restic-backups-kite-full.service\"} |= `snapshot ` |= ` saved`"
    }
   ]
  },
  {
   "title": "Successful snapshots",
   "type": "stat",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({host=\"kite\", source=\"journal\", systemd_unit=\"restic-backups-kite-full.service\"} |= `snapshot ` |= ` saved` [$__auto]))"
    }
   ]
  },
  {
   "title": "Kite Restic journal",
   "type": "logs",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{host=\"kite\", source=\"journal\", systemd_unit=\"restic-backups-kite-full.service\"}"
    }
   ]
  }
 ]
}