secret_key: ENC[AES256_GCM,data:vA4PuBhL+NswPg8WuCqWe83gC+3y/NKfPRmYfKuNTprLrvIMGa+2wpT83zL60xjach5g+qXTSyQCmn1unw09Kw==,iv:ryA2LgVpZVtD1w3zI4f5o4Uk+gaeqpg6F8JG9xcAyGA=,tag:L/mSJ7zh1iJs9NPNKQ0pcA==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDzhdCoWE/CiY3laW9R/I5UEhQs7krz8ur8OOg7su5MJ
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG5aZmtYZyB1RXNE
            QllIZDJzNjliMzY4SmhpYzRIUWF4enBIMXdjOUV6cUZUek5na2pvCkE1aXRpNktM
            ZHBVb2dVbGZ4bFRUV1FNQklUYmtvT1QydVRJVXhZUFh2NEUKLS0tIGQ1ZmwxemZz
            OVdmN2Jab29HeVZMZTlmWHBtYWIyYXQyM3VJQ1hUNy9yTkEK031HhnkIMHHKDl8o
            O+ty1Xi+JSKeYLU8awJE9AndJveFTK3NVIG4UhBfrako5oaSZYxU7FmAs9CVxIPs
            cyPGUw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1p46dg990257vmdzxjutu5ujgjep2wax6z5tapgthkp6kelptu9cs80zc99
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhV3N0S2xUMXVZK0NUNzRM
            dVJ4UWdRSExZK0RFaERsZXRzRkpoQVd1KzBFCkF1cjMraDY5WXlHTFA5NnJVUGtt
            VHZaVnlodC9DKzZ2NVFUN0RSYUsxWlEKLS0tIHlzVGJUNDY3RlR2RCs5VWs0QXM5
            QVRHaFJTeXpSc2htTWJLb3RxQ0lOUm8KLb8TTE+MbXRBdyUU5JUEEXmCIUCrJcir
            QvV8Ho5A96fMks78djV/I8ZjNPqMgK3Mm6uQqjmbikfr5oGAl4vVXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-11T13:45:11Z"
    mac: ENC[AES256_GCM,data:ODkdEtPf/L4RPGQZpyI+TkvcPdaHySUmiGn/8u4BNcWuHB92/6djFWzSUL2k52aKahR95F1L+7FXG6eP2GH6LseGSDRe5cICfsijplBdcI+fvthR5ctG44JyrtRs6XwIKw5wK1G/5B5SrmsEZgUye7gH3Oaz86FTjUjkQX1w5II=,iv:V7CQrawCdIFfDS8Ve3GscN608AQidypSyEf1B7/4QMw=,tag:TqKHgJd6q/RNtSAeYuggKg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
