secret_key: ENC[AES256_GCM,data:jZiogKz4YF+XMK6I7lteLI5xfm7Wvyk42RnRBntoj03tHygPjsyjDtLwRzcr3ZLgx6WdvSbY85x5vF0pGBjGkw==,iv:Amy7UVv1dKunQLdsqNpHEn4dHT756y6uGfA3cIaww5c=,tag:+Ocz9yDSwmTA/xF1jfTA+Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG5aZmtYZyBtaE5u
            WUVLNSszMldxM3pGSW5QUG95bjJNaTRRM0VJS0wvN3lMRXNQNW00CmhzUlVkN29z
            QWxLVWtUREFNZnRiVVhYUnhMTG1TR2lMZWo0RFhDOGd3TU0KLS0tIFgyanJtTFhY
            UmljaVg5Ym80alluT2FJZDRvRGhpSmpoSUdBQ0tmQWNBMzgKA4NDfg30XDcgH8n0
            sLm1YTZhujqT0Pgi37De1p5+i/feJ3MtTl1W5FlTI3LFLu9GYSDidU+ztBlTFxm1
            L0afhg==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDzhdCoWE/CiY3laW9R/I5UEhQs7krz8ur8OOg7su5MJ
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLd2djT21BSlVwTlk4WWhq
            TTViMDB0dGt6Sm82U05iWGZSdFR5TmNxL0JZClFsKytnQS9FUG9RSXl4bEI5NTcy
            eFVLZXIrRVF5RytYa0F3OUNLd2dEbncKLS0tICtJMXdtRndCalJUQU84aEJ3WWNh
            QWRvVDR4Y0JJa2NxZ2djZExjeUhXdmMKXny1hYRzjbF1ZhkQmmW8/AvlhBgpXYne
            8mljRrfKILYwqiFC96IvOU6V2WvYGsO4RnE1dkFfTqV0cRX2aNCStw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p46dg990257vmdzxjutu5ujgjep2wax6z5tapgthkp6kelptu9cs80zc99
    lastmodified: "2026-09-11T13:55:28Z"
    mac: ENC[AES256_GCM,data:3wf1bczR1Ol/xM5g7IbYh0wA+AgkZifTnmSOYF+X7xGYnQLpdTcB2lrC57sZZv7ACAdSYQjeNTF7mx6i1sLPXoCyWBTsOZeSe2xSV97opIOHcEgv2Gdee4AfnqFdLbcA4hWE6VQJrlrWB4wBevX3jBsfE7w/XS1/wrERHdOmxKA=,iv:eV9TKAhOdOxm3u9ETqeBW+NbxHMpNvsfB7/of2t+P8Q=,tag:ov7/62SU1M7BIkvFNR3Sow==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
