secret_key: ENC[AES256_GCM,data:jZiogKz4YF+XMK6I7lteLI5xfm7Wvyk42RnRBntoj03tHygPjsyjDtLwRzcr3ZLgx6WdvSbY85x5vF0pGBjGkw==,iv:Amy7UVv1dKunQLdsqNpHEn4dHT756y6uGfA3cIaww5c=,tag:+Ocz9yDSwmTA/xF1jfTA+Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IExYeE1aUSAwYS85
            Ymx2VzM1NldWTXJYb3l6blNLZmp2dVU3M1pHdnE1NVkwYVgrVm1nCkVaaFFXbzRy
            b29UWEw4NXFCS0hvNk9NbXZqWCtOazMxNVRiZmsxQ0dEc0EKLS0tIHBLVVdJWmsw
            ZXd2OEs4a2V0ZVZ2VDJEWG5LUzY5NTFsWjc0RkJNbWVCMncKgounjsqXUSEpEA7K
            yZfOkAb64YvkpgKl9qEAe8eTRUU9BhYJhvUqBB0MW80Y/OfUGFcC1H7kuZt0MZvU
            SjNrsg==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGW8YuC9dt9wq2LptMHCfrg8n5l0nGUAd227vWCbqKUD
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG5aZmtYZyBOczRy
            Y01nUUxtOGJMcjMyR1NvUVA0eVFTQzN3aDVHN253QVBHREpNbXlNCmlESWhBZlVV
            Z1ZVdUgraldOSktRWlFzUUFYYUVJQlUvWDNWVkllTGsrNlUKLS0tIDZhUnBuTnMx
            Y2FEbFFYSDN0RHViZWRVK0dtOTFoVnh3TmhVQWNDQTRsbFEKIe3IQ3plJN31yUf0
            iUgMSiRgSQ2dlhxXCdLOapaWcWZGmGswy21bM4dKeThCkQNCj88Q0tRg2G/VoXrQ
            FKT3HQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDzhdCoWE/CiY3laW9R/I5UEhQs7krz8ur8OOg7su5MJ
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdE9uQTFTTlFObFM4Mitw
            bjczNjNiQUlKeEEvN1l2am1OdnhZNmNGNDFrCmZYOTU0QWxsTnJvUHIrRi81V01i
            UmdlRklGVXVGNWJuN0RWbG5sZDFGck0KLS0tIGRGVU1ISUNZdzkwSFRKUVhvYXRz
            YzNLZG1aZmhXUFp6NG8xYWkwWlNRNTgKAFJgpnZyw7OB5kDJjszL7kXklCYd0W4e
            6RKgb+Ei+sXcul7cYYrFGwpPnq819R9/rPpqu3sz4BH0VsyGehvz4A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p46dg990257vmdzxjutu5ujgjep2wax6z5tapgthkp6kelptu9cs80zc99
    lastmodified: "2026-09-11T13:55:28Z"
    mac: ENC[AES256_GCM,data:3wf1bczR1Ol/xM5g7IbYh0wA+AgkZifTnmSOYF+X7xGYnQLpdTcB2lrC57sZZv7ACAdSYQjeNTF7mx6i1sLPXoCyWBTsOZeSe2xSV97opIOHcEgv2Gdee4AfnqFdLbcA4hWE6VQJrlrWB4wBevX3jBsfE7w/XS1/wrERHdOmxKA=,iv:eV9TKAhOdOxm3u9ETqeBW+NbxHMpNvsfB7/of2t+P8Q=,tag:ov7/62SU1M7BIkvFNR3Sow==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
