name: ci

on:
  pull_request:

jobs:
  terraform:
    name: terraform
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
      - name: terraform fmt
        run: terraform fmt -check -recursive
      - name: terraform init (no backend)
        run: terraform -chdir=terraform init -backend=false
      - name: terraform validate
        run: terraform -chdir=terraform validate
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: terraform

  nix:
    name: nix
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: flake check
        run: nix flake check --no-update-lock-file
